version: "3"

services:
  rkn_exporter:
    build:
      context: .
    ports:
      - 8080:8080
    command:
      - 'python3'
      - 'rkn_exporter.py'
      - '--ip_in_label'
    environment:
      - APP_IP=0.0.0.0
      - APP_PORT=8080
      - APP_CHECK_INTERVAL=3600
      - APP_DOMAINS=/app/inputs/domains.txt
      # get actual list of blocked ips here:
      # https://reestr.rublacklist.net/api/v2/ips/json/
      # It's also available to use this url in the variable below instead of file
      # rkn-exporter receives file or url
      - APP_SUBNETS=/app/inputs/blocked_subnets.txt
      - APP_THREADS_COUNT=10
      - APP_DNS=8.8.8.8
      - LOG_LEVEL=DEBUG
    volumes:
      - ./inputs:/app/inputs

  prometheus:
    image: prom/prometheus:v2.28.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
