version: "3"

services:
  rkn_exporter:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - APP_PORT=8080
      - APP_CHECK_INTERVAL=60
      - LOG_LEVEL=DEBUG
    volumes:
      - ./:/app/
