version: "3"

services:
  rkn_exporter:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - APP_IP=0.0.0.0
      - APP_PORT=8080
      - APP_CHECK_INTERVAL=3600
      - APP_DOMAINS=/app/inputs/domains.txt
      - APP_SUBNETS=https://reestr.rublacklist.net/api/v2/ips/json/
      - LOG_LEVEL=DEBUG
    volumes:
      - ./:/app/

  prometheus:
    image: prom/prometheus:v2.28.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
